./miniFE.openacc.cpu nx=8 | tee skokkos-result-minife-cpu-s8.txt
./miniFE.openacc.cpu nx=8 | tee -a skokkos-result-minife-cpu-s8.txt
./miniFE.openacc.cpu nx=8 | tee -a skokkos-result-minife-cpu-s8.txt
./miniFE.openacc.cpu nx=16 | tee skokkos-result-minife-cpu-s16.txt
./miniFE.openacc.cpu nx=16 | tee -a skokkos-result-minife-cpu-s16.txt
./miniFE.openacc.cpu nx=16 | tee -a skokkos-result-minife-cpu-s16.txt
./miniFE.openacc.cpu nx=32 | tee skokkos-result-minife-cpu-s32.txt
./miniFE.openacc.cpu nx=32 | tee -a skokkos-result-minife-cpu-s32.txt
./miniFE.openacc.cpu nx=32 | tee -a skokkos-result-minife-cpu-s32.txt
./miniFE.openacc.cpu nx=64 | tee skokkos-result-minife-cpu-s64.txt
./miniFE.openacc.cpu nx=64 | tee -a skokkos-result-minife-cpu-s64.txt
./miniFE.openacc.cpu nx=64 | tee -a skokkos-result-minife-cpu-s64.txt
./miniFE.openacc.cpu nx=128 | tee skokkos-result-minife-cpu-s128.txt
./miniFE.openacc.cpu nx=128 | tee -a skokkos-result-minife-cpu-s128.txt
./miniFE.openacc.cpu nx=128 | tee -a skokkos-result-minife-cpu-s128.txt
./miniFE.openacc.cpu nx=256 | tee skokkos-result-minife-cpu-s256.txt
./miniFE.openacc.cpu nx=256 | tee -a skokkos-result-minife-cpu-s256.txt
./miniFE.openacc.cpu nx=256 | tee -a skokkos-result-minife-cpu-s256.txt
./miniFE.openacc.gpu nx=8 | tee skokkos-result-minife-gpu-s8.txt
./miniFE.openacc.gpu nx=8 | tee -a skokkos-result-minife-gpu-s8.txt
./miniFE.openacc.gpu nx=8 | tee -a skokkos-result-minife-gpu-s8.txt
./miniFE.openacc.gpu nx=16 | tee skokkos-result-minife-gpu-s16.txt
./miniFE.openacc.gpu nx=16 | tee -a skokkos-result-minife-gpu-s16.txt
./miniFE.openacc.gpu nx=16 | tee -a skokkos-result-minife-gpu-s16.txt
./miniFE.openacc.gpu nx=32 | tee skokkos-result-minife-gpu-s32.txt
./miniFE.openacc.gpu nx=32 | tee -a skokkos-result-minife-gpu-s32.txt
./miniFE.openacc.gpu nx=32 | tee -a skokkos-result-minife-gpu-s32.txt
./miniFE.openacc.gpu nx=64 | tee skokkos-result-minife-gpu-s64.txt
./miniFE.openacc.gpu nx=64 | tee -a skokkos-result-minife-gpu-s64.txt
./miniFE.openacc.gpu nx=64 | tee -a skokkos-result-minife-gpu-s64.txt
./miniFE.openacc.gpu nx=128 | tee skokkos-result-minife-gpu-s128.txt
./miniFE.openacc.gpu nx=128 | tee -a skokkos-result-minife-gpu-s128.txt
./miniFE.openacc.gpu nx=128 | tee -a skokkos-result-minife-gpu-s128.txt
./miniFE.openacc.gpu nx=256 | tee skokkos-result-minife-gpu-s256.txt
./miniFE.openacc.gpu nx=256 | tee -a skokkos-result-minife-gpu-s256.txt
./miniFE.openacc.gpu nx=256 | tee -a skokkos-result-minife-gpu-s256.txt
./miniFE.openacc.auto.s8 nx=8 | tee skokkos-result-minife-auto-s8.txt
./miniFE.openacc.auto.s8 nx=8 | tee -a skokkos-result-minife-auto-s8.txt
./miniFE.openacc.auto.s8 nx=8 | tee -a skokkos-result-minife-auto-s8.txt
./miniFE.openacc.auto.s16 nx=16 | tee skokkos-result-minife-auto-s16.txt
./miniFE.openacc.auto.s16 nx=16 | tee -a skokkos-result-minife-auto-s16.txt
./miniFE.openacc.auto.s16 nx=16 | tee -a skokkos-result-minife-auto-s16.txt
./miniFE.openacc.auto.s32 nx=32 | tee skokkos-result-minife-auto-s32.txt
./miniFE.openacc.auto.s32 nx=32 | tee -a skokkos-result-minife-auto-s32.txt
./miniFE.openacc.auto.s32 nx=32 | tee -a skokkos-result-minife-auto-s32.txt
./miniFE.openacc.auto.s64 nx=64 | tee skokkos-result-minife-auto-s64.txt
./miniFE.openacc.auto.s64 nx=64 | tee -a skokkos-result-minife-auto-s64.txt
./miniFE.openacc.auto.s64 nx=64 | tee -a skokkos-result-minife-auto-s64.txt
./miniFE.openacc.auto.s128 nx=128 | tee skokkos-result-minife-auto-s128.txt
./miniFE.openacc.auto.s128 nx=128 | tee -a skokkos-result-minife-auto-s128.txt
./miniFE.openacc.auto.s128 nx=128 | tee -a skokkos-result-minife-auto-s128.txt
./miniFE.openacc.auto.s256 nx=256 | tee skokkos-result-minife-auto-s256.txt
./miniFE.openacc.auto.s256 nx=256 | tee -a skokkos-result-minife-auto-s256.txt
./miniFE.openacc.auto.s256 nx=256 | tee -a skokkos-result-minife-auto-s256.txt
